\set ON_ERROR_STOP on

\ir 'Changes/0001 Add database_version table.sql'
\ir 'Changes/0002 Initial database schema.sql'
\ir 'Changes/0003 Minor changes on validator, event, tx and block tables.sql'
\ir 'Changes/0004 Add geo_location column to validator table.sql'
\ir 'Changes/0005 Add foreign key indexes.sql'
\ir 'Changes/0006 Add unique key constraints.sql'
\ir 'Changes/0007 Add indexes on hash columns.sql'
\ir 'Changes/0008 Remove redundant indexes on hash columns.sql'
\ir 'Changes/0009 Add unique key constraints on transaction and block tables.sql'
\ir 'Changes/0010 Add index controller_address on account table.sql'
\ir 'Changes/0011 Change type of consensus_step in equivocation table.sql'
\ir 'Changes/0012 Add date_time column to tx table.sql'
\ir 'Changes/0013 Rename constraints, add NOT NULL constraints and rename holding and tx tables.sql'
\ir 'Changes/0014 Add grouping_id to blockchain_event table.sql'
